### ISSUE TITLE
errors while starting

### ISSUE THREAD

**Issue by Bluscream** [nukeop/RelayBot2.0#43]
```
(venv) blu@minopia:~/bots/steam/RelayBot $ python relaybot/relaybot.py
/home/blu/bots/steam/RelayBot/venv/lib/python3.7/site-packages/gevent/monkey.py:992: MonkeyPatchWarning: Monkey-patching ssl after ssl has already been imported may lead to errors, including RecursionError on Python 3.6. It may also silently lead to incorrect behaviour on Python 3.7. Please monkey-patch earlier. See https://github.com/gevent/gevent/issues/1016. Modules that had direct imports (NOT patched): ['requests.packages.urllib3.util (/home/blu/bots/steam/RelayBot/venv/lib/python3.7/site-packages/requests/packages/urllib3/util/__init__.py)', 'requests.packages.urllib3.util.ssl_ (/home/blu/bots/steam/RelayBot/venv/lib/python3.7/site-packages/requests/packages/urllib3/util/ssl_.py)'].
  _warnings)
[INFO] - 2020-04-26 23:53:49,304 - root - Scanning plugins...
[INFO] - 2020-04-26 23:53:49,305 - root - Detected plugin: tweet
[ERROR] - 2020-04-26 23:53:49,307 - root - Invalid plugin: tweet
[ERROR] - 2020-04-26 23:53:49,307 - root - No module named 'twitter'
[INFO] - 2020-04-26 23:53:49,308 - root - Detected plugin: leave
[ERROR] - 2020-04-26 23:53:49,309 - root - Invalid plugin: leave
[ERROR] - 2020-04-26 23:53:49,309 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,309 - root - Detected plugin: urbandictionary
[ERROR] - 2020-04-26 23:53:49,311 - root - Invalid plugin: urbandictionary
[ERROR] - 2020-04-26 23:53:49,311 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,311 - root - Detected plugin: admin
[ERROR] - 2020-04-26 23:53:49,313 - root - Invalid plugin: admin
[ERROR] - 2020-04-26 23:53:49,313 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,313 - root - Detected plugin: logs
[ERROR] - 2020-04-26 23:53:49,315 - root - Invalid plugin: logs
[ERROR] - 2020-04-26 23:53:49,315 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,315 - root - Detected plugin: joke
[ERROR] - 2020-04-26 23:53:49,316 - root - Invalid plugin: joke
[ERROR] - 2020-04-26 23:53:49,316 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,317 - root - Detected plugin: weather
[ERROR] - 2020-04-26 23:53:49,318 - root - Invalid plugin: weather
[ERROR] - 2020-04-26 23:53:49,318 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,318 - root - Detected plugin: silence
[ERROR] - 2020-04-26 23:53:49,319 - root - Invalid plugin: silence
[ERROR] - 2020-04-26 23:53:49,320 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,320 - root - Detected plugin: terminal
[ERROR] - 2020-04-26 23:53:49,322 - root - Invalid plugin: terminal
[ERROR] - 2020-04-26 23:53:49,323 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,323 - root - Detected plugin: help
[ERROR] - 2020-04-26 23:53:49,324 - root - Invalid plugin: help
[ERROR] - 2020-04-26 23:53:49,324 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,324 - root - Detected plugin: version
[ERROR] - 2020-04-26 23:53:49,326 - root - Invalid plugin: version
[ERROR] - 2020-04-26 23:53:49,326 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,326 - root - Detected plugin: duckduckgo
[ERROR] - 2020-04-26 23:53:49,327 - root - Invalid plugin: duckduckgo
[ERROR] - 2020-04-26 23:53:49,327 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,328 - root - Detected plugin: trivia
[ERROR] - 2020-04-26 23:53:49,329 - root - Invalid plugin: trivia
[ERROR] - 2020-04-26 23:53:49,329 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,329 - root - Detected plugin: nsa
[ERROR] - 2020-04-26 23:53:49,331 - root - Invalid plugin: nsa
[ERROR] - 2020-04-26 23:53:49,331 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,331 - root - Detected plugin: movie
[ERROR] - 2020-04-26 23:53:49,332 - root - Invalid plugin: movie
[ERROR] - 2020-04-26 23:53:49,332 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,332 - root - Detected plugin: youtube
[ERROR] - 2020-04-26 23:53:49,334 - root - Invalid plugin: youtube
[ERROR] - 2020-04-26 23:53:49,334 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,334 - root - Detected plugin: insult
[ERROR] - 2020-04-26 23:53:49,335 - root - Invalid plugin: insult
[ERROR] - 2020-04-26 23:53:49,335 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,336 - root - Detected plugin: github
[ERROR] - 2020-04-26 23:53:49,337 - root - Invalid plugin: github
[ERROR] - 2020-04-26 23:53:49,337 - root - No module named 'github3'
[INFO] - 2020-04-26 23:53:49,337 - root - Detected plugin: spillthebeans
[ERROR] - 2020-04-26 23:53:49,338 - root - Invalid plugin: spillthebeans
[ERROR] - 2020-04-26 23:53:49,339 - root - No module named 'eventregistry'
[INFO] - 2020-04-26 23:53:49,339 - root - Detected plugin: note
[ERROR] - 2020-04-26 23:53:49,340 - root - Invalid plugin: note
[ERROR] - 2020-04-26 23:53:49,340 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,340 - root - Detected plugin: stock
[ERROR] - 2020-04-26 23:53:49,342 - root - Invalid plugin: stock
[ERROR] - 2020-04-26 23:53:49,342 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,342 - root - Detected plugin: games
[ERROR] - 2020-04-26 23:53:49,343 - root - Invalid plugin: games
[ERROR] - 2020-04-26 23:53:49,344 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,344 - root - Detected plugin: eightball
[ERROR] - 2020-04-26 23:53:49,345 - root - Invalid plugin: eightball
[ERROR] - 2020-04-26 23:53:49,345 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,345 - root - Detected plugin: echo
[ERROR] - 2020-04-26 23:53:49,347 - root - Invalid plugin: echo
[ERROR] - 2020-04-26 23:53:49,347 - root - No module named 'plugin'
[INFO] - 2020-04-26 23:53:49,347 - root - Detected plugin: plugin
[INFO] - 2020-04-26 23:53:49,348 - root - Starting Relay Bot 2.0
[INFO] - 2020-04-26 23:53:49,348 - root - Version: 2.0.4
[DEBUG] - 2020-04-26 23:53:49,349 - CMServerList - Bootstraping from builtin list
[DEBUG] - 2020-04-26 23:53:49,349 - CMServerList - Added 20 new CM addresses.
[INFO] - 2020-04-26 23:53:49,351 - user - Creating a User instance
[DEBUG] - 2020-04-26 23:53:49,351 - Connection - Attempting connection to ('162.254.198.131', 27017)
[DEBUG] - 2020-04-26 23:53:49,429 - Connection - Connected.
[DEBUG] - 2020-04-26 23:53:50,127 - Connection - Connection error (reader).
[DEBUG] - 2020-04-26 23:53:50,128 - Connection - Disconnected.
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
TypeError: handle_errors() missing 1 required positional argument: 'result'
2020-04-26T21:53:50Z <Greenlet at 0xb5479e40: handle_errors(<EResult.AccountLoginDeniedNeedTwoFactor: 85>)> failed with TypeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 854, in gevent._greenlet.Greenlet.run
  File "/home/blu/bots/steam/RelayBot/relaybot/user.py", line 198, in auth_code_prompt
    code = raw_input("Enter Steam Mobile Authenticator code: ")
NameError: name 'raw_input' is not defined
2020-04-26T21:53:50Z <Greenlet at 0xb5479e40: <bound method User.auth_code_prompt of <user.User object at 0xb4fb6390>>(True, False)> failed with NameError

[ERROR] - 2020-04-26 23:53:50,161 - errors - Traceback (most recent call last):
  File "relaybot/relaybot.py", line 124, in <module>
    main()
  File "relaybot/relaybot.py", line 118, in main
    bot.initialize()
  File "relaybot/relaybot.py", line 63, in initialize
    steam.client.SteamClient()
  File "/home/blu/bots/steam/RelayBot/relaybot/user.py", line 64, in __init__
    msg = self.client.wait_event(EMsg.ClientAccountInfo)
  File "/home/blu/bots/steam/RelayBot/venv/lib/python3.7/site-packages/eventemitter/__init__.py", line 119, in wait_event
    return result.get(True, timeout)
  File "src/gevent/event.py", line 279, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 304, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 178, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 196, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 182, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
gevent.exceptions.LoopExit: This operation would block forever
        Hub: <Hub '' at 0xb4f8c690 epoll default pending=0 ref=0 fileno=4 resolver=<gevent.resolver.thread.Resolver at 0xb4fb69f0 pool=<ThreadPool at 0xb4e39998 tasks=0 size=1 maxsize=10 hub=<Hub at 0xb4f8c690 thread_ident=0xb6f96010>>> threadpool=<ThreadPool at 0xb4e39998 tasks=0 size=1 maxsize=10 hub=<Hub at 0xb4f8c690 thread_ident=0xb6f96010>> thread_ident=0xb6f96010>
        Handles:
[]

```

**Comment by nukeop** [comment]
I stopped development around  4 years ago. Since then, steam chat has undergone a huge update, which likely renders this bot obsolete. I will mark this repo as archived, since its only value is probably gone.
